name: Build LineageOS for gauguin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup env
        run: |
          sudo apt install openjdk-8-jdk repo bc ...
          repo init -u https://github.com/LineageOS/android.git -b lineage-20.0
          repo sync -j4

      - name: Clone device tree, kernel, vendor
        run: |
          git clone https://github.com/LineageOS/android_device_xiaomi_gauguin.git device/xiaomi/gauguin
          git clone https://github.com/LineageOS/android_kernel_xiaomi_gauguin.git kernel/xiaomi/gauguin
          git clone https://github.com/LineageOS/android_vendor_lineage.git vendor/xiaomi/gauguin

      - name: Build ROM
        run: |
          source build/envsetup.sh
          lunch lineage_gauguin-userdebug
          mka bacon

      - name: Upload ROM
        uses: actions/upload-artifact@v3
        with:
          name: lineageos-gauguin.zip
          path: out/target/product/gauguin/*.zip

